import { Box, Button, Divider, Flex, Heading, Link, Stack, Stat, StatHelpText, StatLabel, StatNumber, Text } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Bullets from '../components/Bullets'
import Header from '../components/Header'
import Nav from '../components/Nav'
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Aprenda Inglês - Francês Divers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        direction='column'
        align='center'
        width='100%'
      >
        <Nav />
        <Header />
        <Bullets />
        <Stack align='center' justify='center' mt='20' spacing='16'>
          <Heading size='xl' width='75%' textAlign='center'>Uma doutora e um professor de língua nativa!</Heading>
          <Stack direction='row' spacing='24'>
            <Flex bg='white.900' width='250px' height='400px' justify='center' align='center'>
              imagem professores
            </Flex>
            <Flex bg='white.900' width='250px' height='400px' justify='center' align='center'>
              imagem professores
            </Flex>
          </Stack>
          <Text color='black.50' fontSize='16' width='60%' textAlign='center'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis <strong> ipsum harum explicabo nam excepturi  </strong>, blanditiis doloribus quas recusandae debitis veniam ratione nesciunt culpa aperiam odio sequi. Adipisci, eum? Distinctio!</Text>
        </Stack>
        <Stack spacing='6' mt='32' align='center'>
          <Heading textAlign='center' width='60%'>Até quando você irá postergar o início dos seus estudos em francês?
          </Heading>
          <Text fontSize='14' color='orange.50'>Restam poucas vagas para nosso curso INICIANTE de francês.
          </Text>
        </Stack>
        <Stack mt='20' direction='row' spacing='24' align='center'>

          <Stack p='8' width='20rem' border='2px solid #D87353' borderRadius='xl' spacing='8' justify='center' shadow='2xl' align='center'>
            <Heading size='md' color='black.500'>Plano Padrão</Heading>
            <Text color='black.500' fontSize='12' textAlign='center'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat, in.</Text>
            <Divider w='100%' />
            <Stack direction='row' align='flex-end'>
              <Heading fontSize='2xl'>R$ 25,99</Heading>
              <Text color='black.50' fontSize='12'>/ por mês</Text>
            </Stack>
            <Button w='100%' background='transparent' color='orange.500' border='1px solid #D87353' _hover={{ backgroundColor: 'orange.500', color: 'white.500' }}>Quero agora!</Button>
            <Stack align='center' spacing='2'>
              <Text color='black.50'>Firts Availiable</Text>
              <Text color='black.50' fontWeight='bold'>Trainer</Text>
              <Text color='black.50'>Bullet point</Text>
            </Stack>
            <Divider w='100%' />
            <Link fontSize='12' color='orange.50' fontWeight='normal'>Entrar em contato</Link>
          </Stack>

          <Stack p='8' width='22rem' backgroundColor='blue.500' borderRadius='xl' spacing='8' justify='center' shadow='2xl' align='center'>
            <Heading size='xl' color='white.500'>Plano Premium</Heading>
            <Text color='white.500' fontSize='12' textAlign='center'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat, in.</Text>
            <Divider w='100%' />
            <Stack direction='row' align='flex-end'>
              <Heading fontSize='4xl'>R$ 47,99</Heading>
              <Text color='white.50' fontSize='12'>/ por mês</Text>
            </Stack>
            <Button w='100%' variant='solid' _hover={{ backgroundColor: 'orange.500', color: 'white.500' }}>Quero agora!</Button>
            <Stack align='center' spacing='2'>
              <Text color='white.50'>Firts Availiable</Text>
              <Text color='white.50' fontWeight='bold'>Trainer</Text>
              <Text color='white.50'>Bullet point</Text>
            </Stack>
            <Divider w='100%' />
            <Link fontSize='12' color='white.50' fontWeight='normal'>Entrar em contato</Link>
          </Stack>
        </Stack>
        <Flex mt='32' backgroundColor='orange.500' w='100%' h='50vh'></Flex>
      </Flex>
    </>

  )
}

export default Home
